create table member
(
    id bigint generated by default as identity,
    userId varchar(255) not null,
    password varchar(255) not null,
    userName varchar(255) not null,
    userYear number(4) not null,
    userMonth number(4) not null,
    userDate number(4) not null,
    primary key (id)
);

